### ISSUE TITLE
On adding a tag it just goes to the next card

### ISSUE THREAD

**Issue by ghost** [ohspite/anki-tag-toggler#3]
If I tag added on question state then goes to next card in question state,
otherwise goes to answer state of next question.

Really want to use this plugin but this is making it unusable. Thanks.

**Comment by ghost** [comment]
Would really appreciate a fix

**Comment by donm** [comment]
Hi, and thanks for reporting this.  I will release a fix, but it might be a week or two before I get to it.  In the meantime, please let me know the following:

Is the following the problem you're having? 
1. When a question is shown, click `Show Answer`.
2. Hit a key that is configured in this plugin to add a tag and bury or suspend the card.
3. The next card is shown, but with the answer already displayed.
If so, that is indeed a bug and will be fixed.  

Please let me know your operating system, version of Anki, version of TagToggler (it's in the first line of the plugin code), and your configuration options (you can just copy and paste the code in this section:

```
########################################
## CONFIGURATION OPTIONS
(your settings here)
## END CONFIGURATION
########################################
```

After pasting the configuration section into this discussion, highlight it and click the `<>` button so that it is displayed as code.

Finally, it seems like you were saying that adding the tag to a card in question state shows the next card in question state--is that what you would expect?  If not, you can remove the `'after'` key in the settings for your keybinding.  For example,
```
'Shift+T': {'tags': 'TODO', 'after': 'bury-card'}
```
will add the TODO tag and then bury the card, switching to the next card automatically.  If you want to add the tag but stay on the card (and not bury it), you could change that line to
```
'Shift+T': {'tags': 'TODO'}
```

**Comment by tete1030** [comment]
Having same problem. I'm not using 'after' key, but after I tag a card in question state and answer state, anki sometimes, not always, goes to next card. I think `mw.reset()` may trigger some randomization process and cause current card changed. It seems unnecessary to `mw.reset()` when value of `after` is empty and the Quick_Tagging extension does not do this when just adding tag. See https://github.com/cayennes/Quick_Tagging/blob/master/quick_tagging.py

**Comment by donm** [comment]
Okay, @tete1030 and @forums2012: try the changes in 72e07d8 and let me know if that fixes the issue for you, and if it causes anything else to break on your end.

The reason for the call to `mw.reset()` (even when there are no changes to the database) was to force the card to redraw.  When `{{Tags}}` is used in the template it's disconcerting not seeing the changes on the card after you hit a tag's shortcut key.  But it does seem like `reset()` was causing the issue, so this is trying a different method.

**Comment by tete1030** [comment]
Thanks. I will try it and tell you if any problem.

**Comment by glutanimate** [comment]
Thanks for the update, @ohspite. I was experiencing the same issue, but the latest commit fixed it!

**Comment by donm** [comment]
Great, thanks for letting me know.

**Comment by tete1030** [comment]
have tested for 10 days and this fix is good. Sorry for late reply.
